### ISSUE TITLE
not working at all 

### ISSUE THREAD

**Issue by tmmes** [LivelySource/DM-BOT#11]
**tried to host the bot on heroku and all the platforms that i can host the bot and its not working its giving me an error** 
can anyone help me 
the error :

(node:16708) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
 
(node:16708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate
the Node.js process with a non-zero exit code.

**Comment by Mhankk** [comment]
Solution: Update Discord.js to v12

Why does this error occur?
Your bot encountered a [Stage Channel](https://support.discord.com/hc/en-us/articles/1500005513722-Stage-Channels-FAQ), Discord.js v11 does not - and will not - support stage channels. This is essentially the end of the road for v11.

Statement by Discord.js maintainers

Version 11 will hard crash if it encounters a stage channel
• we will not fix this
• please update your bot to version 12 https://v12.discordjs.guide/additional-info/changes-in-v12.html#before-you-start
• reminder: logging in with a user token is against discord terms of service and we fully dropped support for user accounts in version 12.

I already make pull request, i think all the error is caused by discord.js version
